# -*- coding: utf-8 -*-
"""SiteSeekerModelTrainingNotebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_WX3ghG6VTRueygpitX_PL0nXI_mHJb

# SiteSeeker Model Training
"""

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/model"

!pip install ultralytics

# Commented out IPython magic to ensure Python compatibility.
import torch
from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/model/v5_Mosquito-Breeding-Grounds-2-15/Training (AdamW)/train/weights/best.pt')

# %cd "/content/drive/MyDrive/model/v5_Mosquito-Breeding-Grounds-2-14"

model.train(
    data='data.yaml',
    epochs=50,
    batch=32,
    imgsz=640,
    project="Training (AdamW2)",
    optimizer='AdamW',
    lr0=1e-5,
    lrf=0.01,
    warmup_epochs=10,
    patience=15,
    dropout=0.3,
)

